print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(True and True and True)
print(True and True and False)
print(False and False and True)
print(True and False and True and False)
print(False and False and False)
print(True and True and False and True and True)


print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(True or True or True)
print(True or False or True)
print(False or False or True)
print(False or False or True or False or False)
print(True or False or True or False)
print(False or False or False or False)


print(False and False or True)
print(False or True and False)
print(True and True or True and False or True)
print(True or False and False or True or False)
print(False or False and True or True and False)


print((5>1) and (8<5))
print((9<=8) or (8<4))
print((5>=1) and (8<=3))
print((7==7) and (8!=9))
print((8==3)or (9>8) and (7<3))